### ISSUE TITLE
Not sure how to resolve this jq error

### ISSUE THREAD

**Issue by Suleman-Elahi** [tbiehn/CURRYFINGER#1]
![image](https://user-images.githubusercontent.com/24384996/65484100-0b851600-debc-11e9-8062-2b3cc40e7f63.png)

**Comment by tbiehn** [comment]
This isn't the right place to ask for help with the Shodan API and jq. But, I think you might be illuminated by stripping jq away and looking at the raw curl output.

**Comment by Suleman-Elahi** [comment]
I was using CURRYFINGER and stuck here.
